[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "android-control-center"
version = "0.1.0"
description = "Professional Android management suite for Linux"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "PySide6>=6.11"
]

[tool.black]
line-length = 88

[tool.ruff]
line-length = 88

[tool.pytest.ini_options]
testpaths = ["tests"]